markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: panxw
author: "飞飞"
email: chengxiangfeiangel#163.com
name: "飞飞的学习笔记"
url: http://chengxiangfei.github.io
all_categories: [
["python", "Python","/posts/python.html"], 
["meachine", "机器学习","/posts/meachine.html"],
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
